create table tbl_dbbackup (
  field_null date,
  field_bigint bigint,
  field_numeric numeric,
  field_decimal decimal,
  field_integer integer,
  field_float float,
  field_real real,
  field_double double,
  field_smallint smallint,
  field_tinyint tinyint,
  field_timestamp timestamp,
  field_time time,
  field_date date,
  field_blob blob,
  field_clob clob,
  field_varchar varchar,
  field_varchar_ignorecase varchar_ignorecase,
  field_boolean boolean,
);