SELECT
COL.TABLE_NAME "table_name",
COUNT(*) "qtd_columns",
MAX(CON.COLUMN_LIST) "pk_column",
MAX(CASE WHEN COL.TYPE_NAME IN ('BLOB', 'CLOB') THEN 1 ELSE 0 END) "lob"
FROM INFORMATION_SCHEMA.COLUMNS COL
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINTS CON
  ON CON.TABLE_NAME = COL.TABLE_NAME
  AND CON.CONSTRAINT_TYPE = 'PRIMARY KEY'
WHERE COL.TABLE_SCHEMA = :TABLE_SCHEMA
GROUP BY COL.TABLE_NAME
ORDER BY COL.TABLE_NAME