SELECT TABLE_NAME AS "table_name", COLUMN_NAME AS "column_name", TYPE_NAME AS "data_type"
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = :TABLE_SCHEMA
AND (:TABLE_NAME IS NULL OR TABLE_NAME IN (:TABLE_NAME_AR))
ORDER BY TABLE_NAME, ORDINAL_POSITION