SELECT
   SATC.TABLE_NAME as "table_name",
   count(*) "qtd_columns",
   MAX(PK.COLUMN_NAME) "pk_column",
   MAX(CASE WHEN SATC.DATA_TYPE IN ('BLOB', 'CLOB') THEN 1 ELSE 0 END) "lob"
FROM SYS.ALL_TAB_COLUMNS SATC
JOIN SYS.ALL_TABLES SAT ON SAT.OWNER = SATC.OWNER AND SAT.TABLE_NAME = SATC.TABLE_NAME
LEFT JOIN SYS.ALL_MVIEWS SAM ON SAM.OWNER = SATC.OWNER AND SAM.MVIEW_NAME = SATC.TABLE_NAME
LEFT JOIN (
  SELECT SACC.TABLE_NAME, LISTAGG(SACC.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY SACC.COLUMN_NAME) COLUMN_NAME
  FROM ALL_CONS_COLUMNS SACC
  JOIN ALL_CONSTRAINTS SAC
  ON SAC.CONSTRAINT_NAME = SACC.CONSTRAINT_NAME
  AND SAC.OWNER = SACC.OWNER
  AND SAC.TABLE_NAME = SACC.TABLE_NAME
  WHERE SACC.OWNER = :TABLE_SCHEMA
    AND SAC.CONSTRAINT_TYPE = 'P'
  GROUP BY SACC.TABLE_NAME
) PK ON PK.TABLE_NAME = SATC.TABLE_NAME AND PK.COLUMN_NAME = SATC.COLUMN_NAME
WHERE SAM.MVIEW_NAME IS NULL
AND SATC.OWNER = :TABLE_SCHEMA
GROUP BY SATC.TABLE_NAME
ORDER BY SATC.TABLE_NAME