-- oracle 12
alter session set "_ORACLE_SCRIPT"=true;

-- tablespace
CREATE TABLESPACE TS_DBBACKUP DATAFILE 'TS_DBBACKUP' SIZE 5M;

-- USER SQL
CREATE USER "DBBACKUP" IDENTIFIED BY "010203"
DEFAULT TABLESPACE "TS_DBBACKUP"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "DBBACKUP" QUOTA UNLIMITED ON TS_DBBACKUP;

-- SYSTEM PRIVILEGES
GRANT CONNECT TO DBBACKUP;
GRANT UPDATE ANY TABLE TO "DBBACKUP" ;
GRANT CREATE TABLE TO "DBBACKUP" ;
GRANT SELECT ANY TABLE TO "DBBACKUP" ;
GRANT INSERT ANY TABLE TO "DBBACKUP" ;
GRANT DROP ANY TABLE TO "DBBACKUP" ;
GRANT ALTER ANY TABLE TO "DBBACKUP" ;
GRANT CREATE ANY TABLE TO "DBBACKUP" ;
GRANT DELETE ANY TABLE TO "DBBACKUP" ;
GRANT COMMENT ANY TABLE TO "DBBACKUP" ;